version: 2

project_name: terraform-provider-ccplant

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-ccplant
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
    ldflags:
      - "-s -w -X main.version={{ .Version }}"

archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"

release:
  github:
    owner: takutakahashi
    name: terraform-provider-ccplant
